// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEventsByEntity = `-- name: CountAuditEventsByEntity :one
SELECT COUNT(*) FROM audit_events
WHERE entity_type = $1 AND entity_id = $2
`

type CountAuditEventsByEntityParams struct {
	EntityType string
	EntityID   string
}

func (q *Queries) CountAuditEventsByEntity(ctx context.Context, arg CountAuditEventsByEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEventsByEntity, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events( event_type, entity_type, entity_id, actor_id, payload)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, event_type, entity_type, entity_id, actor_id, payload, created_at, expires_at
`

type CreateAuditEventParams struct {
	EventType  string
	EntityType string
	EntityID   string
	ActorID    pgtype.UUID
	Payload    []byte
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.Payload,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.ActorID,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAuditEventsByEntity = `-- name: GetAuditEventsByEntity :many
SELECT id, event_type, entity_type, entity_id, actor_id, payload, created_at, expires_at FROM audit_events 
WHERE entity_type = $1 AND entity_id = $2 
ORDER BY created_at
`

type GetAuditEventsByEntityParams struct {
	EntityType string
	EntityID   string
}

func (q *Queries) GetAuditEventsByEntity(ctx context.Context, arg GetAuditEventsByEntityParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditEventsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditEventsByEntityPaginated = `-- name: GetAuditEventsByEntityPaginated :many
SELECT id, event_type, entity_type, entity_id, actor_id, payload, created_at, expires_at FROM audit_events
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at
LIMIT $3 OFFSET $4
`

type GetAuditEventsByEntityPaginatedParams struct {
	EntityType string
	EntityID   string
	Limit      int32
	Offset     int32
}

func (q *Queries) GetAuditEventsByEntityPaginated(ctx context.Context, arg GetAuditEventsByEntityPaginatedParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditEventsByEntityPaginated,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
