// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claims.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countClaimsByBatch = `-- name: CountClaimsByBatch :one
SELECT COUNT(*) FROM claims
WHERE batch_id = $1
`

func (q *Queries) CountClaimsByBatch(ctx context.Context, batchID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimsByBatch, batchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClaim = `-- name: CreateClaim :one
INSERT INTO claims (batch_id, row_id, org_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, batch_id, org_id, row_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type, status, created_at, adjudication_date, fill_date, reconciliation_status, updated_at
`

type CreateClaimParams struct {
	BatchID     uuid.UUID
	RowID       uuid.UUID
	OrgID       uuid.UUID
	Ndc         string
	PharmacyNpi string
	ServiceDate pgtype.Date
	Quantity    int32
	HashedRxKey pgtype.Text
	PayerType   pgtype.Text
}

func (q *Queries) CreateClaim(ctx context.Context, arg CreateClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, createClaim,
		arg.BatchID,
		arg.RowID,
		arg.OrgID,
		arg.Ndc,
		arg.PharmacyNpi,
		arg.ServiceDate,
		arg.Quantity,
		arg.HashedRxKey,
		arg.PayerType,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OrgID,
		&i.RowID,
		&i.Ndc,
		&i.PharmacyNpi,
		&i.ServiceDate,
		&i.Quantity,
		&i.HashedRxKey,
		&i.PayerType,
		&i.Status,
		&i.CreatedAt,
		&i.AdjudicationDate,
		&i.FillDate,
		&i.ReconciliationStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimByID = `-- name: GetClaimByID :one
SELECT id, batch_id, org_id, row_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type, status, created_at, adjudication_date, fill_date, reconciliation_status, updated_at FROM claims WHERE id = $1
`

func (q *Queries) GetClaimByID(ctx context.Context, id uuid.UUID) (Claim, error) {
	row := q.db.QueryRow(ctx, getClaimByID, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OrgID,
		&i.RowID,
		&i.Ndc,
		&i.PharmacyNpi,
		&i.ServiceDate,
		&i.Quantity,
		&i.HashedRxKey,
		&i.PayerType,
		&i.Status,
		&i.CreatedAt,
		&i.AdjudicationDate,
		&i.FillDate,
		&i.ReconciliationStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimsByBatch = `-- name: GetClaimsByBatch :many
SELECT id, batch_id, org_id, row_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type, status, created_at, adjudication_date, fill_date, reconciliation_status, updated_at FROM claims
WHERE batch_id = $1
ORDER BY created_at
`

func (q *Queries) GetClaimsByBatch(ctx context.Context, batchID uuid.UUID) ([]Claim, error) {
	rows, err := q.db.Query(ctx, getClaimsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.OrgID,
			&i.RowID,
			&i.Ndc,
			&i.PharmacyNpi,
			&i.ServiceDate,
			&i.Quantity,
			&i.HashedRxKey,
			&i.PayerType,
			&i.Status,
			&i.CreatedAt,
			&i.AdjudicationDate,
			&i.FillDate,
			&i.ReconciliationStatus,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaimsByBatchPaginated = `-- name: GetClaimsByBatchPaginated :many
SELECT id, batch_id, org_id, row_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type, status, created_at, adjudication_date, fill_date, reconciliation_status, updated_at FROM claims
WHERE batch_id = $1
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type GetClaimsByBatchPaginatedParams struct {
	BatchID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) GetClaimsByBatchPaginated(ctx context.Context, arg GetClaimsByBatchPaginatedParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, getClaimsByBatchPaginated, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.OrgID,
			&i.RowID,
			&i.Ndc,
			&i.PharmacyNpi,
			&i.ServiceDate,
			&i.Quantity,
			&i.HashedRxKey,
			&i.PayerType,
			&i.Status,
			&i.CreatedAt,
			&i.AdjudicationDate,
			&i.FillDate,
			&i.ReconciliationStatus,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsForRxRehash = `-- name: ListClaimsForRxRehash :many
SELECT c.id, c.hashed_rx_key, ur.data
FROM claims c
INNER JOIN upload_rows ur ON ur.id = c.row_id
WHERE c.hashed_rx_key IS NOT NULL AND btrim(c.hashed_rx_key) <> ''
`

type ListClaimsForRxRehashRow struct {
	ID          uuid.UUID
	HashedRxKey pgtype.Text
	Data        []byte
}

func (q *Queries) ListClaimsForRxRehash(ctx context.Context) ([]ListClaimsForRxRehashRow, error) {
	rows, err := q.db.Query(ctx, listClaimsForRxRehash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimsForRxRehashRow
	for rows.Next() {
		var i ListClaimsForRxRehashRow
		if err := rows.Scan(&i.ID, &i.HashedRxKey, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClaimHashedRxKey = `-- name: UpdateClaimHashedRxKey :exec
UPDATE claims SET hashed_rx_key = $2, updated_at = now() WHERE id = $1
`

type UpdateClaimHashedRxKeyParams struct {
	ID          uuid.UUID
	HashedRxKey pgtype.Text
}

func (q *Queries) UpdateClaimHashedRxKey(ctx context.Context, arg UpdateClaimHashedRxKeyParams) error {
	_, err := q.db.Exec(ctx, updateClaimHashedRxKey, arg.ID, arg.HashedRxKey)
	return err
}
