// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: export_runs.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExportRun = `-- name: CreateExportRun :one
INSERT INTO export_runs (org_id, manufacturer_id, report_type, status, requested_by, params)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, manufacturer_id, report_type, status, file_path, row_count, requested_by, params, error_message, created_at, completed_at
`

type CreateExportRunParams struct {
	OrgID          pgtype.UUID
	ManufacturerID pgtype.UUID
	ReportType     string
	Status         string
	RequestedBy    pgtype.UUID
	Params         []byte
}

func (q *Queries) CreateExportRun(ctx context.Context, arg CreateExportRunParams) (ExportRun, error) {
	row := q.db.QueryRow(ctx, createExportRun,
		arg.OrgID,
		arg.ManufacturerID,
		arg.ReportType,
		arg.Status,
		arg.RequestedBy,
		arg.Params,
	)
	var i ExportRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ManufacturerID,
		&i.ReportType,
		&i.Status,
		&i.FilePath,
		&i.RowCount,
		&i.RequestedBy,
		&i.Params,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getExportRunByID = `-- name: GetExportRunByID :one
SELECT id, org_id, manufacturer_id, report_type, status, file_path, row_count, requested_by, params, error_message, created_at, completed_at FROM export_runs WHERE id = $1
`

func (q *Queries) GetExportRunByID(ctx context.Context, id uuid.UUID) (ExportRun, error) {
	row := q.db.QueryRow(ctx, getExportRunByID, id)
	var i ExportRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ManufacturerID,
		&i.ReportType,
		&i.Status,
		&i.FilePath,
		&i.RowCount,
		&i.RequestedBy,
		&i.Params,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateExportRunCompleted = `-- name: UpdateExportRunCompleted :exec
UPDATE export_runs
SET status      = 'completed',
    file_path   = $2,
    row_count   = $3,
    completed_at = now()
WHERE id = $1
`

type UpdateExportRunCompletedParams struct {
	ID       uuid.UUID
	FilePath pgtype.Text
	RowCount pgtype.Int4
}

func (q *Queries) UpdateExportRunCompleted(ctx context.Context, arg UpdateExportRunCompletedParams) error {
	_, err := q.db.Exec(ctx, updateExportRunCompleted, arg.ID, arg.FilePath, arg.RowCount)
	return err
}

const updateExportRunFailed = `-- name: UpdateExportRunFailed :exec
UPDATE export_runs
SET status        = 'failed',
    error_message = $2,
    completed_at  = now()
WHERE id = $1
`

type UpdateExportRunFailedParams struct {
	ID           uuid.UUID
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateExportRunFailed(ctx context.Context, arg UpdateExportRunFailedParams) error {
	_, err := q.db.Exec(ctx, updateExportRunFailed, arg.ID, arg.ErrorMessage)
	return err
}

const updateExportRunStarted = `-- name: UpdateExportRunStarted :exec
UPDATE export_runs
SET status = 'running'
WHERE id = $1
`

func (q *Queries) UpdateExportRunStarted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateExportRunStarted, id)
	return err
}
