// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manufacturers.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countManufacturers = `-- name: CountManufacturers :one
SELECT COUNT(*) FROM manufacturers
`

func (q *Queries) CountManufacturers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countManufacturers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByManufacturer = `-- name: CountProductsByManufacturer :one
SELECT COUNT(*) FROM manufacturer_products
WHERE manufacturer_id = $1
`

func (q *Queries) CountProductsByManufacturer(ctx context.Context, manufacturerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByManufacturer, manufacturerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManufacturer = `-- name: CreateManufacturer :one
INSERT INTO manufacturers (name, labeler_code)
VALUES ($1, $2)
RETURNING id, name, labeler_code, created_at
`

type CreateManufacturerParams struct {
	Name        string
	LabelerCode string
}

func (q *Queries) CreateManufacturer(ctx context.Context, arg CreateManufacturerParams) (Manufacturer, error) {
	row := q.db.QueryRow(ctx, createManufacturer, arg.Name, arg.LabelerCode)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LabelerCode,
		&i.CreatedAt,
	)
	return i, err
}

const createManufacturerProduct = `-- name: CreateManufacturerProduct :one
INSERT INTO manufacturer_products (manufacturer_id, ndc, product_name)
VALUES ($1, $2, $3)
RETURNING id, manufacturer_id, ndc, product_name, created_at
`

type CreateManufacturerProductParams struct {
	ManufacturerID uuid.UUID
	Ndc            string
	ProductName    pgtype.Text
}

func (q *Queries) CreateManufacturerProduct(ctx context.Context, arg CreateManufacturerProductParams) (ManufacturerProduct, error) {
	row := q.db.QueryRow(ctx, createManufacturerProduct, arg.ManufacturerID, arg.Ndc, arg.ProductName)
	var i ManufacturerProduct
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.Ndc,
		&i.ProductName,
		&i.CreatedAt,
	)
	return i, err
}

const getManufacturerByID = `-- name: GetManufacturerByID :one
SELECT id, name, labeler_code, created_at FROM manufacturers WHERE id = $1
`

func (q *Queries) GetManufacturerByID(ctx context.Context, id uuid.UUID) (Manufacturer, error) {
	row := q.db.QueryRow(ctx, getManufacturerByID, id)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LabelerCode,
		&i.CreatedAt,
	)
	return i, err
}

const getManufacturerByLabelerCode = `-- name: GetManufacturerByLabelerCode :one
SELECT id, name, labeler_code, created_at FROM manufacturers WHERE labeler_code = $1
`

func (q *Queries) GetManufacturerByLabelerCode(ctx context.Context, labelerCode string) (Manufacturer, error) {
	row := q.db.QueryRow(ctx, getManufacturerByLabelerCode, labelerCode)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LabelerCode,
		&i.CreatedAt,
	)
	return i, err
}

const getManufacturerByNDC = `-- name: GetManufacturerByNDC :one
SELECT m.id, m.name, m.labeler_code, m.created_at FROM manufacturers m
JOIN manufacturer_products mp ON mp.manufacturer_id = m.id
WHERE mp.ndc = $1
`

func (q *Queries) GetManufacturerByNDC(ctx context.Context, ndc string) (Manufacturer, error) {
	row := q.db.QueryRow(ctx, getManufacturerByNDC, ndc)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LabelerCode,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByNDC = `-- name: GetProductByNDC :one
SELECT id, manufacturer_id, ndc, product_name, created_at FROM manufacturer_products WHERE ndc = $1
`

func (q *Queries) GetProductByNDC(ctx context.Context, ndc string) (ManufacturerProduct, error) {
	row := q.db.QueryRow(ctx, getProductByNDC, ndc)
	var i ManufacturerProduct
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.Ndc,
		&i.ProductName,
		&i.CreatedAt,
	)
	return i, err
}

const listManufacturers = `-- name: ListManufacturers :many
SELECT id, name, labeler_code, created_at FROM manufacturers ORDER BY name
`

func (q *Queries) ListManufacturers(ctx context.Context) ([]Manufacturer, error) {
	rows, err := q.db.Query(ctx, listManufacturers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Manufacturer
	for rows.Next() {
		var i Manufacturer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LabelerCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManufacturersPaginated = `-- name: ListManufacturersPaginated :many
SELECT id, name, labeler_code, created_at FROM manufacturers
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListManufacturersPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListManufacturersPaginated(ctx context.Context, arg ListManufacturersPaginatedParams) ([]Manufacturer, error) {
	rows, err := q.db.Query(ctx, listManufacturersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Manufacturer
	for rows.Next() {
		var i Manufacturer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LabelerCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByManufacturer = `-- name: ListProductsByManufacturer :many
SELECT id, manufacturer_id, ndc, product_name, created_at FROM manufacturer_products
WHERE manufacturer_id = $1
ORDER BY ndc
`

func (q *Queries) ListProductsByManufacturer(ctx context.Context, manufacturerID uuid.UUID) ([]ManufacturerProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByManufacturer, manufacturerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManufacturerProduct
	for rows.Next() {
		var i ManufacturerProduct
		if err := rows.Scan(
			&i.ID,
			&i.ManufacturerID,
			&i.Ndc,
			&i.ProductName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByManufacturerPaginated = `-- name: ListProductsByManufacturerPaginated :many
SELECT id, manufacturer_id, ndc, product_name, created_at FROM manufacturer_products
WHERE manufacturer_id = $1
ORDER BY ndc
LIMIT $2 OFFSET $3
`

type ListProductsByManufacturerPaginatedParams struct {
	ManufacturerID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListProductsByManufacturerPaginated(ctx context.Context, arg ListProductsByManufacturerPaginatedParams) ([]ManufacturerProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByManufacturerPaginated, arg.ManufacturerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManufacturerProduct
	for rows.Next() {
		var i ManufacturerProduct
		if err := rows.Scan(
			&i.ID,
			&i.ManufacturerID,
			&i.Ndc,
			&i.ProductName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
