// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manual_overrides.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createManualOverride = `-- name: CreateManualOverride :one
INSERT INTO manual_override_events (claim_id, previous_status, new_status, reason, rebate_record_id, overridden_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, claim_id, previous_status, new_status, reason, rebate_record_id, overridden_by, created_at
`

type CreateManualOverrideParams struct {
	ClaimID        uuid.UUID
	PreviousStatus string
	NewStatus      string
	Reason         string
	RebateRecordID pgtype.UUID
	OverriddenBy   uuid.UUID
}

func (q *Queries) CreateManualOverride(ctx context.Context, arg CreateManualOverrideParams) (ManualOverrideEvent, error) {
	row := q.db.QueryRow(ctx, createManualOverride,
		arg.ClaimID,
		arg.PreviousStatus,
		arg.NewStatus,
		arg.Reason,
		arg.RebateRecordID,
		arg.OverriddenBy,
	)
	var i ManualOverrideEvent
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.PreviousStatus,
		&i.NewStatus,
		&i.Reason,
		&i.RebateRecordID,
		&i.OverriddenBy,
		&i.CreatedAt,
	)
	return i, err
}

const getManualOverridesByClaim = `-- name: GetManualOverridesByClaim :many
SELECT id, claim_id, previous_status, new_status, reason, rebate_record_id, overridden_by, created_at FROM manual_override_events
WHERE claim_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetManualOverridesByClaim(ctx context.Context, claimID uuid.UUID) ([]ManualOverrideEvent, error) {
	rows, err := q.db.Query(ctx, getManualOverridesByClaim, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualOverrideEvent
	for rows.Next() {
		var i ManualOverrideEvent
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.PreviousStatus,
			&i.NewStatus,
			&i.Reason,
			&i.RebateRecordID,
			&i.OverriddenBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchDecisionOverride = `-- name: UpdateMatchDecisionOverride :exec
UPDATE match_decisions
SET status      = $2,
    override_id = $3
WHERE claim_id = $1
`

type UpdateMatchDecisionOverrideParams struct {
	ClaimID    uuid.UUID
	Status     string
	OverrideID pgtype.UUID
}

func (q *Queries) UpdateMatchDecisionOverride(ctx context.Context, arg UpdateMatchDecisionOverrideParams) error {
	_, err := q.db.Exec(ctx, updateMatchDecisionOverride, arg.ClaimID, arg.Status, arg.OverrideID)
	return err
}
