// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_backup_codes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const consumeMfaBackupCode = `-- name: ConsumeMfaBackupCode :one
UPDATE mfa_backup_codes SET used_at = NOW()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
RETURNING id
`

type ConsumeMfaBackupCodeParams struct {
	UserID   uuid.UUID
	CodeHash string
}

func (q *Queries) ConsumeMfaBackupCode(ctx context.Context, arg ConsumeMfaBackupCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeMfaBackupCode, arg.UserID, arg.CodeHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteMfaBackupCodesForUser = `-- name: DeleteMfaBackupCodesForUser :exec
DELETE FROM mfa_backup_codes WHERE user_id = $1
`

func (q *Queries) DeleteMfaBackupCodesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMfaBackupCodesForUser, userID)
	return err
}

const insertMfaBackupCode = `-- name: InsertMfaBackupCode :exec
INSERT INTO mfa_backup_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertMfaBackupCodeParams struct {
	UserID   uuid.UUID
	CodeHash string
}

func (q *Queries) InsertMfaBackupCode(ctx context.Context, arg InsertMfaBackupCodeParams) error {
	_, err := q.db.Exec(ctx, insertMfaBackupCode, arg.UserID, arg.CodeHash)
	return err
}
