// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID         uuid.UUID
	EventType  string
	EntityType string
	EntityID   string
	ActorID    pgtype.UUID
	Payload    []byte
	CreatedAt  time.Time
	ExpiresAt  pgtype.Timestamptz
}

type CandidateMatch struct {
	ID             uuid.UUID
	JobID          uuid.UUID
	ClaimID        uuid.UUID
	RebateRecordID uuid.UUID
	Score          int32
	CreatedAt      time.Time
}

type CaseComment struct {
	ID        uuid.UUID
	CaseID    uuid.UUID
	AuthorID  uuid.UUID
	Body      string
	CreatedAt time.Time
}

type Claim struct {
	ID                   uuid.UUID
	BatchID              uuid.UUID
	OrgID                uuid.UUID
	RowID                uuid.UUID
	Ndc                  string
	PharmacyNpi          string
	ServiceDate          pgtype.Date
	Quantity             int32
	HashedRxKey          pgtype.Text
	PayerType            pgtype.Text
	Status               string
	CreatedAt            time.Time
	AdjudicationDate     pgtype.Date
	FillDate             pgtype.Date
	ReconciliationStatus string
	UpdatedAt            time.Time
}

type ContractPharmacy struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	PharmacyName  string
	PharmacyNpi   string
	DeaNumber     pgtype.Text
	Address       pgtype.Text
	City          pgtype.Text
	State         pgtype.Text
	Zip           pgtype.Text
	Status        string
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Designation struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	PharmacyID     uuid.UUID
	ManufacturerID string
	EffectiveDate  pgtype.Date
	EndDate        pgtype.Date
	Status         string
	CreatedBy      pgtype.UUID
	CreatedAt      time.Time
}

type Dispute struct {
	ID             uuid.UUID
	ClaimID        uuid.UUID
	OrgID          uuid.UUID
	ManufacturerID uuid.UUID
	Status         string
	ReasonCode     string
	Description    string
	EvidenceRef    pgtype.Text
	Resolution     pgtype.Text
	OpenedBy       uuid.UUID
	ResolvedBy     pgtype.UUID
	OpenedAt       time.Time
	ResolvedAt     pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ExceptionCase struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	ClaimID        pgtype.UUID
	BatchID        pgtype.UUID
	Title          string
	Status         string
	Priority       string
	AssigneeUserID pgtype.UUID
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ExportRun struct {
	ID             uuid.UUID
	OrgID          pgtype.UUID
	ManufacturerID pgtype.UUID
	ReportType     string
	Status         string
	FilePath       pgtype.Text
	RowCount       pgtype.Int4
	RequestedBy    pgtype.UUID
	Params         []byte
	ErrorMessage   pgtype.Text
	CreatedAt      time.Time
	CompletedAt    pgtype.Timestamptz
}

type FeatureFlagOverride struct {
	OrgID     uuid.UUID
	FlagKey   string
	Value     bool
	UpdatedAt time.Time
}

type ManualOverrideEvent struct {
	ID             uuid.UUID
	ClaimID        uuid.UUID
	PreviousStatus string
	NewStatus      string
	Reason         string
	RebateRecordID pgtype.UUID
	OverriddenBy   uuid.UUID
	CreatedAt      time.Time
}

type Manufacturer struct {
	ID          uuid.UUID
	Name        string
	LabelerCode string
	CreatedAt   time.Time
}

type ManufacturerContractPharmacyAuth struct {
	ID                 uuid.UUID
	ManufacturerID     uuid.UUID
	ContractPharmacyID uuid.UUID
	Authorized         bool
	EffectiveFrom      pgtype.Date
	EffectiveTo        pgtype.Date
	CreatedAt          time.Time
}

type ManufacturerProduct struct {
	ID             uuid.UUID
	ManufacturerID uuid.UUID
	Ndc            string
	ProductName    pgtype.Text
	CreatedAt      time.Time
}

type MatchDecision struct {
	ID              uuid.UUID
	JobID           uuid.UUID
	ClaimID         uuid.UUID
	RebateRecordID  pgtype.UUID
	PolicyVersionID pgtype.UUID
	Status          string
	Reasoning       []byte
	CreatedAt       time.Time
	OverrideID      pgtype.UUID
}

type MfaBackupCode struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type OrgSsoConfig struct {
	OrgID            uuid.UUID
	OidcIssuer       pgtype.Text
	OidcClientID     pgtype.Text
	OidcClientSecret pgtype.Text
	Enabled          bool
	UpdatedAt        time.Time
	SamlIdpEntityID  pgtype.Text
	SamlIdpSsoUrl    pgtype.Text
	SamlIdpCertPem   pgtype.Text
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	EntityID  string
	CreatedAt time.Time
}

type OrganizationSetting struct {
	OrgID     uuid.UUID
	Settings  []byte
	UpdatedAt time.Time
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type Pharmacy struct {
	ID        uuid.UUID
	Name      string
	Npi       string
	Address   pgtype.Text
	CreatedAt time.Time
}

type Policy struct {
	ID             uuid.UUID
	ManufacturerID uuid.UUID
	Name           string
	Status         string
	CreatedAt      time.Time
}

type PolicyRule struct {
	ID              uuid.UUID
	PolicyVersionID uuid.UUID
	RuleType        string
	RuleConfig      []byte
	CreatedAt       time.Time
}

type PolicyVersion struct {
	ID            uuid.UUID
	PolicyID      uuid.UUID
	VersionNumber int32
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	CreatedAt     time.Time
}

type RebateRecord struct {
	ID             uuid.UUID
	ManufacturerID uuid.UUID
	OrgID          uuid.UUID
	Ndc            string
	PharmacyNpi    string
	ServiceDate    pgtype.Date
	Quantity       int32
	HashedRxKey    pgtype.Text
	PayerType      pgtype.Text
	RebateAmount   pgtype.Numeric
	Source         string
	Status         string
	CreatedAt      time.Time
}

type ReconciliationJob struct {
	ID                 uuid.UUID
	BatchID            uuid.UUID
	Status             string
	TotalClaims        int32
	MatchedCount       int32
	UnmatchedCount     int32
	DuplicateRiskCount int32
	ExcludedCount      int32
	ErrorCount         int32
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	CreatedAt          time.Time
}

type UploadBatch struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	UploadedBy   uuid.UUID
	FileName     string
	RowCount     int32
	Status       string
	ErrorMessage pgtype.Text
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UploadRow struct {
	ID        uuid.UUID
	BatchID   uuid.UUID
	RowNumber int32
	Data      []byte
	CreatedAt time.Time
}

type User struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	Email               string
	Name                string
	Role                string
	CreatedAt           time.Time
	PasswordHash        string
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	MfaEnabled          bool
	MfaSecret           pgtype.Text
	Active              bool
}

type UserExternalIdentity struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Provider  string
	Issuer    string
	Subject   string
	Email     pgtype.Text
	CreatedAt time.Time
}

type ValidationResult struct {
	ID        uuid.UUID
	RowID     uuid.UUID
	BatchID   uuid.UUID
	IsValid   bool
	Errors    []byte
	CreatedAt time.Time
}

type WebhookDelivery struct {
	ID             uuid.UUID
	SubscriptionID uuid.UUID
	EventType      string
	Payload        []byte
	Status         string
	AttemptCount   int32
	NextRetryAt    pgtype.Timestamptz
	LastError      pgtype.Text
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WebhookSubscription struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Url        string
	SecretHmac string
	EventTypes []string
	Active     bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
