// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExceptionCasesByOrg = `-- name: CountExceptionCasesByOrg :one
SELECT COUNT(*) FROM exception_cases WHERE org_id = $1
`

func (q *Queries) CountExceptionCasesByOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExceptionCasesByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByOrg = `-- name: CountUsersByOrg :one
SELECT COUNT(*) FROM users WHERE org_id = $1
`

func (q *Queries) CountUsersByOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCaseComment = `-- name: CreateCaseComment :one
INSERT INTO case_comments (case_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, case_id, author_id, body, created_at
`

type CreateCaseCommentParams struct {
	CaseID   uuid.UUID
	AuthorID uuid.UUID
	Body     string
}

func (q *Queries) CreateCaseComment(ctx context.Context, arg CreateCaseCommentParams) (CaseComment, error) {
	row := q.db.QueryRow(ctx, createCaseComment, arg.CaseID, arg.AuthorID, arg.Body)
	var i CaseComment
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createExceptionCase = `-- name: CreateExceptionCase :one
INSERT INTO exception_cases (org_id, claim_id, batch_id, title, status, priority, assignee_user_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, claim_id, batch_id, title, status, priority, assignee_user_id, created_by, created_at, updated_at
`

type CreateExceptionCaseParams struct {
	OrgID          uuid.UUID
	ClaimID        pgtype.UUID
	BatchID        pgtype.UUID
	Title          string
	Status         string
	Priority       string
	AssigneeUserID pgtype.UUID
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateExceptionCase(ctx context.Context, arg CreateExceptionCaseParams) (ExceptionCase, error) {
	row := q.db.QueryRow(ctx, createExceptionCase,
		arg.OrgID,
		arg.ClaimID,
		arg.BatchID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.AssigneeUserID,
		arg.CreatedBy,
	)
	var i ExceptionCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClaimID,
		&i.BatchID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (subscription_id, event_type, payload, status, next_retry_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subscription_id, event_type, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	SubscriptionID uuid.UUID
	EventType      string
	Payload        []byte
	Status         string
	NextRetryAt    pgtype.Timestamptz
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.SubscriptionID,
		arg.EventType,
		arg.Payload,
		arg.Status,
		arg.NextRetryAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one
INSERT INTO webhook_subscriptions (org_id, url, secret_hmac, event_types, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, url, secret_hmac, event_types, active, created_at, updated_at
`

type CreateWebhookSubscriptionParams struct {
	OrgID      uuid.UUID
	Url        string
	SecretHmac string
	EventTypes []string
	Active     bool
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.OrgID,
		arg.Url,
		arg.SecretHmac,
		arg.EventTypes,
		arg.Active,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.SecretHmac,
		&i.EventTypes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :exec
DELETE FROM webhook_subscriptions WHERE id = $1 AND org_id = $2
`

type DeleteWebhookSubscriptionParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookSubscription, arg.ID, arg.OrgID)
	return err
}

const getExceptionCase = `-- name: GetExceptionCase :one
SELECT id, org_id, claim_id, batch_id, title, status, priority, assignee_user_id, created_by, created_at, updated_at FROM exception_cases WHERE id = $1 AND org_id = $2
`

type GetExceptionCaseParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetExceptionCase(ctx context.Context, arg GetExceptionCaseParams) (ExceptionCase, error) {
	row := q.db.QueryRow(ctx, getExceptionCase, arg.ID, arg.OrgID)
	var i ExceptionCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClaimID,
		&i.BatchID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureFlagOverride = `-- name: GetFeatureFlagOverride :one
SELECT org_id, flag_key, value, updated_at FROM feature_flag_overrides WHERE org_id = $1 AND flag_key = $2
`

type GetFeatureFlagOverrideParams struct {
	OrgID   uuid.UUID
	FlagKey string
}

func (q *Queries) GetFeatureFlagOverride(ctx context.Context, arg GetFeatureFlagOverrideParams) (FeatureFlagOverride, error) {
	row := q.db.QueryRow(ctx, getFeatureFlagOverride, arg.OrgID, arg.FlagKey)
	var i FeatureFlagOverride
	err := row.Scan(
		&i.OrgID,
		&i.FlagKey,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgSSOConfig = `-- name: GetOrgSSOConfig :one
SELECT org_id, oidc_issuer, oidc_client_id, oidc_client_secret, enabled, updated_at, saml_idp_entity_id, saml_idp_sso_url, saml_idp_cert_pem FROM org_sso_config WHERE org_id = $1
`

func (q *Queries) GetOrgSSOConfig(ctx context.Context, orgID uuid.UUID) (OrgSsoConfig, error) {
	row := q.db.QueryRow(ctx, getOrgSSOConfig, orgID)
	var i OrgSsoConfig
	err := row.Scan(
		&i.OrgID,
		&i.OidcIssuer,
		&i.OidcClientID,
		&i.OidcClientSecret,
		&i.Enabled,
		&i.UpdatedAt,
		&i.SamlIdpEntityID,
		&i.SamlIdpSsoUrl,
		&i.SamlIdpCertPem,
	)
	return i, err
}

const getOrganizationSettings = `-- name: GetOrganizationSettings :one
SELECT org_id, settings, updated_at FROM organization_settings WHERE org_id = $1
`

func (q *Queries) GetOrganizationSettings(ctx context.Context, orgID uuid.UUID) (OrganizationSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationSettings, orgID)
	var i OrganizationSetting
	err := row.Scan(&i.OrgID, &i.Settings, &i.UpdatedAt)
	return i, err
}

const getUserByIDForOrg = `-- name: GetUserByIDForOrg :one
SELECT id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
FROM users WHERE id = $1 AND org_id = $2
`

type GetUserByIDForOrgParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetUserByIDForOrg(ctx context.Context, arg GetUserByIDForOrgParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDForOrg, arg.ID, arg.OrgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}

const getUserExternalIdentityByIssuerSubject = `-- name: GetUserExternalIdentityByIssuerSubject :one
SELECT id, user_id, provider, issuer, subject, email, created_at FROM user_external_identities WHERE issuer = $1 AND subject = $2
`

type GetUserExternalIdentityByIssuerSubjectParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetUserExternalIdentityByIssuerSubject(ctx context.Context, arg GetUserExternalIdentityByIssuerSubjectParams) (UserExternalIdentity, error) {
	row := q.db.QueryRow(ctx, getUserExternalIdentityByIssuerSubject, arg.Issuer, arg.Subject)
	var i UserExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookSubscription = `-- name: GetWebhookSubscription :one
SELECT id, org_id, url, secret_hmac, event_types, active, created_at, updated_at FROM webhook_subscriptions WHERE id = $1 AND org_id = $2
`

type GetWebhookSubscriptionParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetWebhookSubscription(ctx context.Context, arg GetWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscription, arg.ID, arg.OrgID)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.SecretHmac,
		&i.EventTypes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookSubscriptionByID = `-- name: GetWebhookSubscriptionByID :one
SELECT id, org_id, url, secret_hmac, event_types, active, created_at, updated_at FROM webhook_subscriptions WHERE id = $1
`

func (q *Queries) GetWebhookSubscriptionByID(ctx context.Context, id uuid.UUID) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscriptionByID, id)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.SecretHmac,
		&i.EventTypes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserExternalIdentity = `-- name: InsertUserExternalIdentity :one
INSERT INTO user_external_identities (user_id, provider, issuer, subject, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, issuer, subject, email, created_at
`

type InsertUserExternalIdentityParams struct {
	UserID   uuid.UUID
	Provider string
	Issuer   string
	Subject  string
	Email    pgtype.Text
}

func (q *Queries) InsertUserExternalIdentity(ctx context.Context, arg InsertUserExternalIdentityParams) (UserExternalIdentity, error) {
	row := q.db.QueryRow(ctx, insertUserExternalIdentity,
		arg.UserID,
		arg.Provider,
		arg.Issuer,
		arg.Subject,
		arg.Email,
	)
	var i UserExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listCaseComments = `-- name: ListCaseComments :many
SELECT id, case_id, author_id, body, created_at FROM case_comments WHERE case_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListCaseComments(ctx context.Context, caseID uuid.UUID) ([]CaseComment, error) {
	rows, err := q.db.Query(ctx, listCaseComments, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaseComment
	for rows.Next() {
		var i CaseComment
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExceptionCasesByOrg = `-- name: ListExceptionCasesByOrg :many
SELECT id, org_id, claim_id, batch_id, title, status, priority, assignee_user_id, created_by, created_at, updated_at FROM exception_cases WHERE org_id = $1 ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListExceptionCasesByOrgParams struct {
	OrgID  uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListExceptionCasesByOrg(ctx context.Context, arg ListExceptionCasesByOrgParams) ([]ExceptionCase, error) {
	rows, err := q.db.Query(ctx, listExceptionCasesByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExceptionCase
	for rows.Next() {
		var i ExceptionCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClaimID,
			&i.BatchID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.AssigneeUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlagOverridesByOrg = `-- name: ListFeatureFlagOverridesByOrg :many
SELECT org_id, flag_key, value, updated_at FROM feature_flag_overrides WHERE org_id = $1
`

func (q *Queries) ListFeatureFlagOverridesByOrg(ctx context.Context, orgID uuid.UUID) ([]FeatureFlagOverride, error) {
	rows, err := q.db.Query(ctx, listFeatureFlagOverridesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlagOverride
	for rows.Next() {
		var i FeatureFlagOverride
		if err := rows.Scan(
			&i.OrgID,
			&i.FlagKey,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByOrg = `-- name: ListUsersByOrg :many
SELECT id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
FROM users WHERE org_id = $1 ORDER BY email ASC
`

func (q *Queries) ListUsersByOrg(ctx context.Context, orgID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.PasswordHash,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByOrgPaginated = `-- name: ListUsersByOrgPaginated :many
SELECT id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
FROM users WHERE org_id = $1 ORDER BY email ASC LIMIT $2 OFFSET $3
`

type ListUsersByOrgPaginatedParams struct {
	OrgID  uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsersByOrgPaginated(ctx context.Context, arg ListUsersByOrgPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrgPaginated, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.PasswordHash,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesBySubscription = `-- name: ListWebhookDeliveriesBySubscription :many
SELECT id, subscription_id, event_type, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at FROM webhook_deliveries WHERE subscription_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListWebhookDeliveriesBySubscriptionParams struct {
	SubscriptionID uuid.UUID
	Limit          int32
}

func (q *Queries) ListWebhookDeliveriesBySubscription(ctx context.Context, arg ListWebhookDeliveriesBySubscriptionParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesBySubscription, arg.SubscriptionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesPending = `-- name: ListWebhookDeliveriesPending :many
SELECT id, subscription_id, event_type, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at FROM webhook_deliveries
WHERE status IN ('pending', 'retrying')
  AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListWebhookDeliveriesPending(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesPending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptionsByOrg = `-- name: ListWebhookSubscriptionsByOrg :many
SELECT id, org_id, url, secret_hmac, event_types, active, created_at, updated_at FROM webhook_subscriptions WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWebhookSubscriptionsByOrg(ctx context.Context, orgID uuid.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptionsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookSubscription
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.SecretHmac,
			&i.EventTypes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExceptionCase = `-- name: UpdateExceptionCase :one
UPDATE exception_cases
SET title = $3,
    status = $4,
    priority = $5,
    assignee_user_id = $6,
    updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, claim_id, batch_id, title, status, priority, assignee_user_id, created_by, created_at, updated_at
`

type UpdateExceptionCaseParams struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	Title          string
	Status         string
	Priority       string
	AssigneeUserID pgtype.UUID
}

func (q *Queries) UpdateExceptionCase(ctx context.Context, arg UpdateExceptionCaseParams) (ExceptionCase, error) {
	row := q.db.QueryRow(ctx, updateExceptionCase,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.AssigneeUserID,
	)
	var i ExceptionCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClaimID,
		&i.BatchID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2 WHERE id = $1 AND org_id = $3
RETURNING id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
`

type UpdateUserRoleParams struct {
	ID    uuid.UUID
	Role  string
	OrgID uuid.UUID
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role, arg.OrgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}

const updateWebhookDeliveryStatus = `-- name: UpdateWebhookDeliveryStatus :exec
UPDATE webhook_deliveries SET status = $2, attempt_count = $3, last_error = $4, next_retry_at = $5, updated_at = now()
WHERE id = $1
`

type UpdateWebhookDeliveryStatusParams struct {
	ID           uuid.UUID
	Status       string
	AttemptCount int32
	LastError    pgtype.Text
	NextRetryAt  pgtype.Timestamptz
}

func (q *Queries) UpdateWebhookDeliveryStatus(ctx context.Context, arg UpdateWebhookDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDeliveryStatus,
		arg.ID,
		arg.Status,
		arg.AttemptCount,
		arg.LastError,
		arg.NextRetryAt,
	)
	return err
}

const updateWebhookSubscription = `-- name: UpdateWebhookSubscription :one
UPDATE webhook_subscriptions SET url = $2, event_types = $3, active = $4, updated_at = now()
WHERE id = $1 AND org_id = $5
RETURNING id, org_id, url, secret_hmac, event_types, active, created_at, updated_at
`

type UpdateWebhookSubscriptionParams struct {
	ID         uuid.UUID
	Url        string
	EventTypes []string
	Active     bool
	OrgID      uuid.UUID
}

func (q *Queries) UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, updateWebhookSubscription,
		arg.ID,
		arg.Url,
		arg.EventTypes,
		arg.Active,
		arg.OrgID,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.SecretHmac,
		&i.EventTypes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFeatureFlagOverride = `-- name: UpsertFeatureFlagOverride :one
INSERT INTO feature_flag_overrides (org_id, flag_key, value, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (org_id, flag_key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING org_id, flag_key, value, updated_at
`

type UpsertFeatureFlagOverrideParams struct {
	OrgID   uuid.UUID
	FlagKey string
	Value   bool
}

func (q *Queries) UpsertFeatureFlagOverride(ctx context.Context, arg UpsertFeatureFlagOverrideParams) (FeatureFlagOverride, error) {
	row := q.db.QueryRow(ctx, upsertFeatureFlagOverride, arg.OrgID, arg.FlagKey, arg.Value)
	var i FeatureFlagOverride
	err := row.Scan(
		&i.OrgID,
		&i.FlagKey,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgSSOConfig = `-- name: UpsertOrgSSOConfig :one
INSERT INTO org_sso_config (
  org_id, oidc_issuer, oidc_client_id, oidc_client_secret, enabled,
  saml_idp_entity_id, saml_idp_sso_url, saml_idp_cert_pem, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (org_id) DO UPDATE SET
  oidc_issuer = EXCLUDED.oidc_issuer,
  oidc_client_id = EXCLUDED.oidc_client_id,
  oidc_client_secret = EXCLUDED.oidc_client_secret,
  enabled = EXCLUDED.enabled,
  saml_idp_entity_id = EXCLUDED.saml_idp_entity_id,
  saml_idp_sso_url = EXCLUDED.saml_idp_sso_url,
  saml_idp_cert_pem = EXCLUDED.saml_idp_cert_pem,
  updated_at = now()
RETURNING org_id, oidc_issuer, oidc_client_id, oidc_client_secret, enabled, updated_at, saml_idp_entity_id, saml_idp_sso_url, saml_idp_cert_pem
`

type UpsertOrgSSOConfigParams struct {
	OrgID            uuid.UUID
	OidcIssuer       pgtype.Text
	OidcClientID     pgtype.Text
	OidcClientSecret pgtype.Text
	Enabled          bool
	SamlIdpEntityID  pgtype.Text
	SamlIdpSsoUrl    pgtype.Text
	SamlIdpCertPem   pgtype.Text
}

func (q *Queries) UpsertOrgSSOConfig(ctx context.Context, arg UpsertOrgSSOConfigParams) (OrgSsoConfig, error) {
	row := q.db.QueryRow(ctx, upsertOrgSSOConfig,
		arg.OrgID,
		arg.OidcIssuer,
		arg.OidcClientID,
		arg.OidcClientSecret,
		arg.Enabled,
		arg.SamlIdpEntityID,
		arg.SamlIdpSsoUrl,
		arg.SamlIdpCertPem,
	)
	var i OrgSsoConfig
	err := row.Scan(
		&i.OrgID,
		&i.OidcIssuer,
		&i.OidcClientID,
		&i.OidcClientSecret,
		&i.Enabled,
		&i.UpdatedAt,
		&i.SamlIdpEntityID,
		&i.SamlIdpSsoUrl,
		&i.SamlIdpCertPem,
	)
	return i, err
}

const upsertOrganizationSettings = `-- name: UpsertOrganizationSettings :one
INSERT INTO organization_settings (org_id, settings, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (org_id) DO UPDATE SET settings = EXCLUDED.settings, updated_at = now()
RETURNING org_id, settings, updated_at
`

type UpsertOrganizationSettingsParams struct {
	OrgID    uuid.UUID
	Settings []byte
}

func (q *Queries) UpsertOrganizationSettings(ctx context.Context, arg UpsertOrganizationSettingsParams) (OrganizationSetting, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationSettings, arg.OrgID, arg.Settings)
	var i OrganizationSetting
	err := row.Scan(&i.OrgID, &i.Settings, &i.UpdatedAt)
	return i, err
}
