// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPoliciesByManufacturer = `-- name: CountPoliciesByManufacturer :one
SELECT COUNT(*) FROM policies
WHERE manufacturer_id = $1
`

func (q *Queries) CountPoliciesByManufacturer(ctx context.Context, manufacturerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPoliciesByManufacturer, manufacturerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRulesByPolicyVersion = `-- name: CountRulesByPolicyVersion :one
SELECT COUNT(*) FROM policy_rules
WHERE policy_version_id = $1
`

func (q *Queries) CountRulesByPolicyVersion(ctx context.Context, policyVersionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRulesByPolicyVersion, policyVersionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (manufacturer_id, name, status)
VALUES ($1, $2, $3)
RETURNING id, manufacturer_id, name, status, created_at
`

type CreatePolicyParams struct {
	ManufacturerID uuid.UUID
	Name           string
	Status         string
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy, arg.ManufacturerID, arg.Name, arg.Status)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPolicyRule = `-- name: CreatePolicyRule :one
INSERT INTO policy_rules (policy_version_id, rule_type, rule_config)
VALUES ($1, $2, $3)
RETURNING id, policy_version_id, rule_type, rule_config, created_at
`

type CreatePolicyRuleParams struct {
	PolicyVersionID uuid.UUID
	RuleType        string
	RuleConfig      []byte
}

func (q *Queries) CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error) {
	row := q.db.QueryRow(ctx, createPolicyRule, arg.PolicyVersionID, arg.RuleType, arg.RuleConfig)
	var i PolicyRule
	err := row.Scan(
		&i.ID,
		&i.PolicyVersionID,
		&i.RuleType,
		&i.RuleConfig,
		&i.CreatedAt,
	)
	return i, err
}

const createPolicyVersion = `-- name: CreatePolicyVersion :one
INSERT INTO policy_versions (policy_id, version_number, effective_from, effective_to)
VALUES ($1, $2, $3, $4)
RETURNING id, policy_id, version_number, effective_from, effective_to, created_at
`

type CreatePolicyVersionParams struct {
	PolicyID      uuid.UUID
	VersionNumber int32
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
}

func (q *Queries) CreatePolicyVersion(ctx context.Context, arg CreatePolicyVersionParams) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, createPolicyVersion,
		arg.PolicyID,
		arg.VersionNumber,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i PolicyVersion
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.VersionNumber,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePolicyVersion = `-- name: GetActivePolicyVersion :one
SELECT pv.id, pv.policy_id, pv.version_number, pv.effective_from, pv.effective_to, pv.created_at FROM policy_versions pv
JOIN policies p ON p.id = pv.policy_id
WHERE p.manufacturer_id = $1
  AND pv.effective_from <= $2
  AND (pv.effective_to IS NULL OR pv.effective_to >= $2)
  AND p.status = 'active'
ORDER BY pv.version_number DESC
LIMIT 1
`

type GetActivePolicyVersionParams struct {
	ManufacturerID uuid.UUID
	EffectiveFrom  pgtype.Date
}

func (q *Queries) GetActivePolicyVersion(ctx context.Context, arg GetActivePolicyVersionParams) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, getActivePolicyVersion, arg.ManufacturerID, arg.EffectiveFrom)
	var i PolicyVersion
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.VersionNumber,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT id, manufacturer_id, name, status, created_at FROM policies WHERE id = $1
`

func (q *Queries) GetPolicyByID(ctx context.Context, id uuid.UUID) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyVersionByID = `-- name: GetPolicyVersionByID :one
SELECT id, policy_id, version_number, effective_from, effective_to, created_at FROM policy_versions WHERE id = $1
`

func (q *Queries) GetPolicyVersionByID(ctx context.Context, id uuid.UUID) (PolicyVersion, error) {
	row := q.db.QueryRow(ctx, getPolicyVersionByID, id)
	var i PolicyVersion
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.VersionNumber,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getRulesByPolicyVersion = `-- name: GetRulesByPolicyVersion :many
SELECT id, policy_version_id, rule_type, rule_config, created_at FROM policy_rules
WHERE policy_version_id = $1
ORDER BY created_at
`

func (q *Queries) GetRulesByPolicyVersion(ctx context.Context, policyVersionID uuid.UUID) ([]PolicyRule, error) {
	rows, err := q.db.Query(ctx, getRulesByPolicyVersion, policyVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyRule
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.PolicyVersionID,
			&i.RuleType,
			&i.RuleConfig,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRulesByPolicyVersionPaginated = `-- name: GetRulesByPolicyVersionPaginated :many
SELECT id, policy_version_id, rule_type, rule_config, created_at FROM policy_rules
WHERE policy_version_id = $1
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type GetRulesByPolicyVersionPaginatedParams struct {
	PolicyVersionID uuid.UUID
	Limit           int32
	Offset          int32
}

func (q *Queries) GetRulesByPolicyVersionPaginated(ctx context.Context, arg GetRulesByPolicyVersionPaginatedParams) ([]PolicyRule, error) {
	rows, err := q.db.Query(ctx, getRulesByPolicyVersionPaginated, arg.PolicyVersionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyRule
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.PolicyVersionID,
			&i.RuleType,
			&i.RuleConfig,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesByManufacturer = `-- name: ListPoliciesByManufacturer :many
SELECT id, manufacturer_id, name, status, created_at FROM policies
WHERE manufacturer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPoliciesByManufacturer(ctx context.Context, manufacturerID uuid.UUID) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesByManufacturer, manufacturerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.ManufacturerID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesByManufacturerPaginated = `-- name: ListPoliciesByManufacturerPaginated :many
SELECT id, manufacturer_id, name, status, created_at FROM policies
WHERE manufacturer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPoliciesByManufacturerPaginatedParams struct {
	ManufacturerID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListPoliciesByManufacturerPaginated(ctx context.Context, arg ListPoliciesByManufacturerPaginatedParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesByManufacturerPaginated, arg.ManufacturerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.ManufacturerID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
