// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rebate_records.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRebateRecord = `-- name: CreateRebateRecord :one
INSERT INTO rebate_records (
    manufacturer_id, org_id, ndc, pharmacy_npi,
    service_date, quantity, hashed_rx_key, payer_type,
    rebate_amount, source
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, manufacturer_id, org_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type, rebate_amount, source, status, created_at
`

type CreateRebateRecordParams struct {
	ManufacturerID uuid.UUID
	OrgID          uuid.UUID
	Ndc            string
	PharmacyNpi    string
	ServiceDate    pgtype.Date
	Quantity       int32
	HashedRxKey    pgtype.Text
	PayerType      pgtype.Text
	RebateAmount   pgtype.Numeric
	Source         string
}

func (q *Queries) CreateRebateRecord(ctx context.Context, arg CreateRebateRecordParams) (RebateRecord, error) {
	row := q.db.QueryRow(ctx, createRebateRecord,
		arg.ManufacturerID,
		arg.OrgID,
		arg.Ndc,
		arg.PharmacyNpi,
		arg.ServiceDate,
		arg.Quantity,
		arg.HashedRxKey,
		arg.PayerType,
		arg.RebateAmount,
		arg.Source,
	)
	var i RebateRecord
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.OrgID,
		&i.Ndc,
		&i.PharmacyNpi,
		&i.ServiceDate,
		&i.Quantity,
		&i.HashedRxKey,
		&i.PayerType,
		&i.RebateAmount,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCandidateRebateRecords = `-- name: GetCandidateRebateRecords :many
SELECT id, manufacturer_id, org_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type, rebate_amount, source, status, created_at FROM rebate_records
WHERE ndc          = $1
  AND org_id       = $2
  AND pharmacy_npi = $3
  AND service_date BETWEEN $4 AND $5
  AND status       = 'active'
ORDER BY service_date
`

type GetCandidateRebateRecordsParams struct {
	Ndc           string
	OrgID         uuid.UUID
	PharmacyNpi   string
	ServiceDate   pgtype.Date
	ServiceDate_2 pgtype.Date
}

// Candidate retrieval: fetch records that could match a given claim.
// Called by the reconciliation engine during candidate retrieval (Step A).
func (q *Queries) GetCandidateRebateRecords(ctx context.Context, arg GetCandidateRebateRecordsParams) ([]RebateRecord, error) {
	rows, err := q.db.Query(ctx, getCandidateRebateRecords,
		arg.Ndc,
		arg.OrgID,
		arg.PharmacyNpi,
		arg.ServiceDate,
		arg.ServiceDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RebateRecord
	for rows.Next() {
		var i RebateRecord
		if err := rows.Scan(
			&i.ID,
			&i.ManufacturerID,
			&i.OrgID,
			&i.Ndc,
			&i.PharmacyNpi,
			&i.ServiceDate,
			&i.Quantity,
			&i.HashedRxKey,
			&i.PayerType,
			&i.RebateAmount,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRebateRecordByID = `-- name: GetRebateRecordByID :one
SELECT id, manufacturer_id, org_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type, rebate_amount, source, status, created_at FROM rebate_records WHERE id = $1
`

func (q *Queries) GetRebateRecordByID(ctx context.Context, id uuid.UUID) (RebateRecord, error) {
	row := q.db.QueryRow(ctx, getRebateRecordByID, id)
	var i RebateRecord
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.OrgID,
		&i.Ndc,
		&i.PharmacyNpi,
		&i.ServiceDate,
		&i.Quantity,
		&i.HashedRxKey,
		&i.PayerType,
		&i.RebateAmount,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
