// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconciliation.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMatchDecisionsByJob = `-- name: CountMatchDecisionsByJob :one
SELECT COUNT(*) FROM match_decisions
WHERE job_id = $1
`

func (q *Queries) CountMatchDecisionsByJob(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchDecisionsByJob, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandidateMatch = `-- name: CreateCandidateMatch :one
INSERT INTO candidate_matches (job_id, claim_id, rebate_record_id, score)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, claim_id, rebate_record_id, score, created_at
`

type CreateCandidateMatchParams struct {
	JobID          uuid.UUID
	ClaimID        uuid.UUID
	RebateRecordID uuid.UUID
	Score          int32
}

func (q *Queries) CreateCandidateMatch(ctx context.Context, arg CreateCandidateMatchParams) (CandidateMatch, error) {
	row := q.db.QueryRow(ctx, createCandidateMatch,
		arg.JobID,
		arg.ClaimID,
		arg.RebateRecordID,
		arg.Score,
	)
	var i CandidateMatch
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ClaimID,
		&i.RebateRecordID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const createMatchDecision = `-- name: CreateMatchDecision :one
INSERT INTO match_decisions (
    job_id, claim_id, rebate_record_id,
    policy_version_id, status, reasoning
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, claim_id, rebate_record_id, policy_version_id, status, reasoning, created_at, override_id
`

type CreateMatchDecisionParams struct {
	JobID           uuid.UUID
	ClaimID         uuid.UUID
	RebateRecordID  pgtype.UUID
	PolicyVersionID pgtype.UUID
	Status          string
	Reasoning       []byte
}

func (q *Queries) CreateMatchDecision(ctx context.Context, arg CreateMatchDecisionParams) (MatchDecision, error) {
	row := q.db.QueryRow(ctx, createMatchDecision,
		arg.JobID,
		arg.ClaimID,
		arg.RebateRecordID,
		arg.PolicyVersionID,
		arg.Status,
		arg.Reasoning,
	)
	var i MatchDecision
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ClaimID,
		&i.RebateRecordID,
		&i.PolicyVersionID,
		&i.Status,
		&i.Reasoning,
		&i.CreatedAt,
		&i.OverrideID,
	)
	return i, err
}

const createReconciliationJob = `-- name: CreateReconciliationJob :one
INSERT INTO reconciliation_jobs (batch_id, status, total_claims)
VALUES ($1, $2, $3)
RETURNING id, batch_id, status, total_claims, matched_count, unmatched_count, duplicate_risk_count, excluded_count, error_count, started_at, completed_at, created_at
`

type CreateReconciliationJobParams struct {
	BatchID     uuid.UUID
	Status      string
	TotalClaims int32
}

func (q *Queries) CreateReconciliationJob(ctx context.Context, arg CreateReconciliationJobParams) (ReconciliationJob, error) {
	row := q.db.QueryRow(ctx, createReconciliationJob, arg.BatchID, arg.Status, arg.TotalClaims)
	var i ReconciliationJob
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Status,
		&i.TotalClaims,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.DuplicateRiskCount,
		&i.ExcludedCount,
		&i.ErrorCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchDecisionByClaim = `-- name: GetMatchDecisionByClaim :one
SELECT id, job_id, claim_id, rebate_record_id, policy_version_id, status, reasoning, created_at, override_id FROM match_decisions WHERE claim_id = $1
`

func (q *Queries) GetMatchDecisionByClaim(ctx context.Context, claimID uuid.UUID) (MatchDecision, error) {
	row := q.db.QueryRow(ctx, getMatchDecisionByClaim, claimID)
	var i MatchDecision
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ClaimID,
		&i.RebateRecordID,
		&i.PolicyVersionID,
		&i.Status,
		&i.Reasoning,
		&i.CreatedAt,
		&i.OverrideID,
	)
	return i, err
}

const getMatchDecisionsByJob = `-- name: GetMatchDecisionsByJob :many
SELECT id, job_id, claim_id, rebate_record_id, policy_version_id, status, reasoning, created_at, override_id FROM match_decisions
WHERE job_id = $1
ORDER BY created_at
`

func (q *Queries) GetMatchDecisionsByJob(ctx context.Context, jobID uuid.UUID) ([]MatchDecision, error) {
	rows, err := q.db.Query(ctx, getMatchDecisionsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchDecision
	for rows.Next() {
		var i MatchDecision
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClaimID,
			&i.RebateRecordID,
			&i.PolicyVersionID,
			&i.Status,
			&i.Reasoning,
			&i.CreatedAt,
			&i.OverrideID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchDecisionsByJobPaginated = `-- name: GetMatchDecisionsByJobPaginated :many
SELECT id, job_id, claim_id, rebate_record_id, policy_version_id, status, reasoning, created_at, override_id FROM match_decisions
WHERE job_id = $1
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type GetMatchDecisionsByJobPaginatedParams struct {
	JobID  uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetMatchDecisionsByJobPaginated(ctx context.Context, arg GetMatchDecisionsByJobPaginatedParams) ([]MatchDecision, error) {
	rows, err := q.db.Query(ctx, getMatchDecisionsByJobPaginated, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchDecision
	for rows.Next() {
		var i MatchDecision
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ClaimID,
			&i.RebateRecordID,
			&i.PolicyVersionID,
			&i.Status,
			&i.Reasoning,
			&i.CreatedAt,
			&i.OverrideID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingClaimsByBatch = `-- name: GetPendingClaimsByBatch :many
SELECT id, batch_id, org_id, row_id, ndc, pharmacy_npi, service_date, quantity, hashed_rx_key, payer_type, status, created_at, adjudication_date, fill_date, reconciliation_status, updated_at FROM claims
WHERE batch_id = $1
  AND reconciliation_status = 'pending'
ORDER BY created_at
`

func (q *Queries) GetPendingClaimsByBatch(ctx context.Context, batchID uuid.UUID) ([]Claim, error) {
	rows, err := q.db.Query(ctx, getPendingClaimsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.OrgID,
			&i.RowID,
			&i.Ndc,
			&i.PharmacyNpi,
			&i.ServiceDate,
			&i.Quantity,
			&i.HashedRxKey,
			&i.PayerType,
			&i.Status,
			&i.CreatedAt,
			&i.AdjudicationDate,
			&i.FillDate,
			&i.ReconciliationStatus,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReconciliationJobByBatch = `-- name: GetReconciliationJobByBatch :one
SELECT id, batch_id, status, total_claims, matched_count, unmatched_count, duplicate_risk_count, excluded_count, error_count, started_at, completed_at, created_at FROM reconciliation_jobs WHERE batch_id = $1
`

func (q *Queries) GetReconciliationJobByBatch(ctx context.Context, batchID uuid.UUID) (ReconciliationJob, error) {
	row := q.db.QueryRow(ctx, getReconciliationJobByBatch, batchID)
	var i ReconciliationJob
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Status,
		&i.TotalClaims,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.DuplicateRiskCount,
		&i.ExcludedCount,
		&i.ErrorCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReconciliationJobByID = `-- name: GetReconciliationJobByID :one
SELECT id, batch_id, status, total_claims, matched_count, unmatched_count, duplicate_risk_count, excluded_count, error_count, started_at, completed_at, created_at FROM reconciliation_jobs WHERE id = $1
`

func (q *Queries) GetReconciliationJobByID(ctx context.Context, id uuid.UUID) (ReconciliationJob, error) {
	row := q.db.QueryRow(ctx, getReconciliationJobByID, id)
	var i ReconciliationJob
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Status,
		&i.TotalClaims,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.DuplicateRiskCount,
		&i.ExcludedCount,
		&i.ErrorCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markJobStarted = `-- name: MarkJobStarted :exec
UPDATE reconciliation_jobs
SET status = 'running', started_at = now()
WHERE id = $1
`

func (q *Queries) MarkJobStarted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markJobStarted, id)
	return err
}

const updateClaimReconciliationStatus = `-- name: UpdateClaimReconciliationStatus :exec
UPDATE claims
SET reconciliation_status = $2,
    updated_at            = now()
WHERE id = $1
`

type UpdateClaimReconciliationStatusParams struct {
	ID                   uuid.UUID
	ReconciliationStatus string
}

func (q *Queries) UpdateClaimReconciliationStatus(ctx context.Context, arg UpdateClaimReconciliationStatusParams) error {
	_, err := q.db.Exec(ctx, updateClaimReconciliationStatus, arg.ID, arg.ReconciliationStatus)
	return err
}

const updateJobCounts = `-- name: UpdateJobCounts :exec
UPDATE reconciliation_jobs
SET matched_count        = $2,
    unmatched_count      = $3,
    duplicate_risk_count = $4,
    excluded_count       = $5,
    error_count          = $6,
    completed_at         = now()
WHERE id = $1
`

type UpdateJobCountsParams struct {
	ID                 uuid.UUID
	MatchedCount       int32
	UnmatchedCount     int32
	DuplicateRiskCount int32
	ExcludedCount      int32
	ErrorCount         int32
}

func (q *Queries) UpdateJobCounts(ctx context.Context, arg UpdateJobCountsParams) error {
	_, err := q.db.Exec(ctx, updateJobCounts,
		arg.ID,
		arg.MatchedCount,
		arg.UnmatchedCount,
		arg.DuplicateRiskCount,
		arg.ExcludedCount,
		arg.ErrorCount,
	)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE reconciliation_jobs
SET status = $2
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus, arg.ID, arg.Status)
	return err
}
