// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reporting.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDuplicateDiscountFindings = `-- name: GetDuplicateDiscountFindings :many
SELECT
    c.id          AS claim_id,
    c.org_id,
    c.ndc,
    c.pharmacy_npi,
    c.service_date,
    c.quantity,
    c.payer_type,
    md.reasoning,
    rr.rebate_amount,
    rr.source     AS rebate_source
FROM claims c
JOIN match_decisions md ON md.claim_id = c.id
LEFT JOIN rebate_records rr ON rr.id = md.rebate_record_id
WHERE md.status = 'duplicate_discount_risk'
  AND c.service_date BETWEEN $1 AND $2
ORDER BY c.service_date
`

type GetDuplicateDiscountFindingsParams struct {
	ServiceDate   pgtype.Date
	ServiceDate_2 pgtype.Date
}

type GetDuplicateDiscountFindingsRow struct {
	ClaimID      uuid.UUID
	OrgID        uuid.UUID
	Ndc          string
	PharmacyNpi  string
	ServiceDate  pgtype.Date
	Quantity     int32
	PayerType    pgtype.Text
	Reasoning    []byte
	RebateAmount pgtype.Numeric
	RebateSource pgtype.Text
}

func (q *Queries) GetDuplicateDiscountFindings(ctx context.Context, arg GetDuplicateDiscountFindingsParams) ([]GetDuplicateDiscountFindingsRow, error) {
	rows, err := q.db.Query(ctx, getDuplicateDiscountFindings, arg.ServiceDate, arg.ServiceDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDuplicateDiscountFindingsRow
	for rows.Next() {
		var i GetDuplicateDiscountFindingsRow
		if err := rows.Scan(
			&i.ClaimID,
			&i.OrgID,
			&i.Ndc,
			&i.PharmacyNpi,
			&i.ServiceDate,
			&i.Quantity,
			&i.PayerType,
			&i.Reasoning,
			&i.RebateAmount,
			&i.RebateSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManufacturerComplianceData = `-- name: GetManufacturerComplianceData :many
SELECT
    m.id                                                                         AS manufacturer_id,
    m.name                                                                       AS manufacturer_name,
    m.labeler_code,
    COUNT(md.id)                                                                 AS total_claims,
    COUNT(md.id) FILTER (WHERE md.status = 'matched')                           AS matched_count,
    COUNT(md.id) FILTER (WHERE md.status = 'probable_match')                    AS probable_match_count,
    COUNT(md.id) FILTER (WHERE md.status = 'unmatched')                         AS unmatched_count,
    COUNT(md.id) FILTER (WHERE md.status = 'duplicate_discount_risk')           AS duplicate_risk_count,
    COUNT(md.id) FILTER (WHERE md.status = 'excluded_by_policy')                AS excluded_count,
    COUNT(md.id) FILTER (WHERE md.status = 'invalid')                           AS invalid_count
FROM claims c
JOIN match_decisions md ON md.claim_id = c.id
JOIN manufacturer_products mp ON mp.ndc = c.ndc
JOIN manufacturers m ON m.id = mp.manufacturer_id
WHERE c.service_date BETWEEN $1 AND $2
GROUP BY m.id, m.name, m.labeler_code
ORDER BY m.name
`

type GetManufacturerComplianceDataParams struct {
	ServiceDate   pgtype.Date
	ServiceDate_2 pgtype.Date
}

type GetManufacturerComplianceDataRow struct {
	ManufacturerID     uuid.UUID
	ManufacturerName   string
	LabelerCode        string
	TotalClaims        int64
	MatchedCount       int64
	ProbableMatchCount int64
	UnmatchedCount     int64
	DuplicateRiskCount int64
	ExcludedCount      int64
	InvalidCount       int64
}

func (q *Queries) GetManufacturerComplianceData(ctx context.Context, arg GetManufacturerComplianceDataParams) ([]GetManufacturerComplianceDataRow, error) {
	rows, err := q.db.Query(ctx, getManufacturerComplianceData, arg.ServiceDate, arg.ServiceDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManufacturerComplianceDataRow
	for rows.Next() {
		var i GetManufacturerComplianceDataRow
		if err := rows.Scan(
			&i.ManufacturerID,
			&i.ManufacturerName,
			&i.LabelerCode,
			&i.TotalClaims,
			&i.MatchedCount,
			&i.ProbableMatchCount,
			&i.UnmatchedCount,
			&i.DuplicateRiskCount,
			&i.ExcludedCount,
			&i.InvalidCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStuckBatches = `-- name: GetStuckBatches :many
SELECT id, org_id, uploaded_by, file_name, row_count, status, error_message, created_at, updated_at FROM upload_batches
WHERE status IN ('uploaded', 'normalized')
  AND updated_at < now() - interval '1 hour'
ORDER BY updated_at
`

func (q *Queries) GetStuckBatches(ctx context.Context) ([]UploadBatch, error) {
	rows, err := q.db.Query(ctx, getStuckBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadBatch
	for rows.Next() {
		var i UploadBatch
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UploadedBy,
			&i.FileName,
			&i.RowCount,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionCompleteness = `-- name: GetSubmissionCompleteness :many
SELECT
    o.id                               AS org_id,
    o.name                             AS org_name,
    o.entity_id,
    COUNT(ub.id)                       AS batch_count,
    COALESCE(SUM(ub.row_count), 0)     AS total_rows
FROM organizations o
LEFT JOIN upload_batches ub
       ON ub.org_id = o.id
      AND ub.created_at BETWEEN $1 AND $2
GROUP BY o.id, o.name, o.entity_id
ORDER BY o.name
`

type GetSubmissionCompletenessParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type GetSubmissionCompletenessRow struct {
	OrgID      uuid.UUID
	OrgName    string
	EntityID   string
	BatchCount int64
	TotalRows  interface{}
}

func (q *Queries) GetSubmissionCompleteness(ctx context.Context, arg GetSubmissionCompletenessParams) ([]GetSubmissionCompletenessRow, error) {
	rows, err := q.db.Query(ctx, getSubmissionCompleteness, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionCompletenessRow
	for rows.Next() {
		var i GetSubmissionCompletenessRow
		if err := rows.Scan(
			&i.OrgID,
			&i.OrgName,
			&i.EntityID,
			&i.BatchCount,
			&i.TotalRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnresolvedExceptions = `-- name: GetUnresolvedExceptions :many
SELECT
    c.id              AS claim_id,
    c.org_id,
    c.ndc,
    c.pharmacy_npi,
    c.service_date,
    c.quantity,
    md.status         AS decision_status,
    md.reasoning
FROM claims c
JOIN match_decisions md ON md.claim_id = c.id
WHERE md.status IN ('unmatched', 'pending_external_data')
  AND ($1::uuid IS NULL OR c.org_id = $1)
  AND c.service_date BETWEEN $2 AND $3
ORDER BY c.service_date
`

type GetUnresolvedExceptionsParams struct {
	Column1       uuid.UUID
	ServiceDate   pgtype.Date
	ServiceDate_2 pgtype.Date
}

type GetUnresolvedExceptionsRow struct {
	ClaimID        uuid.UUID
	OrgID          uuid.UUID
	Ndc            string
	PharmacyNpi    string
	ServiceDate    pgtype.Date
	Quantity       int32
	DecisionStatus string
	Reasoning      []byte
}

func (q *Queries) GetUnresolvedExceptions(ctx context.Context, arg GetUnresolvedExceptionsParams) ([]GetUnresolvedExceptionsRow, error) {
	rows, err := q.db.Query(ctx, getUnresolvedExceptions, arg.Column1, arg.ServiceDate, arg.ServiceDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnresolvedExceptionsRow
	for rows.Next() {
		var i GetUnresolvedExceptionsRow
		if err := rows.Scan(
			&i.ClaimID,
			&i.OrgID,
			&i.Ndc,
			&i.PharmacyNpi,
			&i.ServiceDate,
			&i.Quantity,
			&i.DecisionStatus,
			&i.Reasoning,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
