// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_batches.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUploadBatches = `-- name: CreateUploadBatches :one
INSERT INTO upload_batches (org_id, uploaded_by, file_name, row_count, status, error_message)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, org_id, uploaded_by, file_name, row_count, status, error_message, created_at, updated_at
`

type CreateUploadBatchesParams struct {
	OrgID        uuid.UUID
	UploadedBy   uuid.UUID
	FileName     string
	RowCount     int32
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) CreateUploadBatches(ctx context.Context, arg CreateUploadBatchesParams) (UploadBatch, error) {
	row := q.db.QueryRow(ctx, createUploadBatches,
		arg.OrgID,
		arg.UploadedBy,
		arg.FileName,
		arg.RowCount,
		arg.Status,
		arg.ErrorMessage,
	)
	var i UploadBatch
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UploadedBy,
		&i.FileName,
		&i.RowCount,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadBatches = `-- name: GetUploadBatches :one
SELECT id, org_id, uploaded_by, file_name, row_count, status, error_message, created_at, updated_at FROM upload_batches 
WHERE id = $1
`

func (q *Queries) GetUploadBatches(ctx context.Context, id uuid.UUID) (UploadBatch, error) {
	row := q.db.QueryRow(ctx, getUploadBatches, id)
	var i UploadBatch
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UploadedBy,
		&i.FileName,
		&i.RowCount,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBatchStatus = `-- name: UpdateBatchStatus :exec
UPDATE upload_batches
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateBatchStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateBatchStatus(ctx context.Context, arg UpdateBatchStatusParams) error {
	_, err := q.db.Exec(ctx, updateBatchStatus, arg.ID, arg.Status)
	return err
}

const updateBatchStatusWithError = `-- name: UpdateBatchStatusWithError :exec
UPDATE upload_batches
SET status = $2, error_message = $3 , updated_at = now()
WHERE id = $1
`

type UpdateBatchStatusWithErrorParams struct {
	ID           uuid.UUID
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateBatchStatusWithError(ctx context.Context, arg UpdateBatchStatusWithErrorParams) error {
	_, err := q.db.Exec(ctx, updateBatchStatusWithError, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
