// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_rows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUploadRow = `-- name: CreateUploadRow :one
INSERT INTO upload_rows (batch_id, row_number, data)
VALUES ($1,$2,$3)
RETURNING id, batch_id, row_number, data, created_at
`

type CreateUploadRowParams struct {
	BatchID   uuid.UUID
	RowNumber int32
	Data      []byte
}

func (q *Queries) CreateUploadRow(ctx context.Context, arg CreateUploadRowParams) (UploadRow, error) {
	row := q.db.QueryRow(ctx, createUploadRow, arg.BatchID, arg.RowNumber, arg.Data)
	var i UploadRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.RowNumber,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadRowsByBatch = `-- name: GetUploadRowsByBatch :many
SELECT id, batch_id, row_number, data, created_at FROM upload_rows
WHERE batch_id = $1 
ORDER BY row_number
`

func (q *Queries) GetUploadRowsByBatch(ctx context.Context, batchID uuid.UUID) ([]UploadRow, error) {
	rows, err := q.db.Query(ctx, getUploadRowsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadRow
	for rows.Next() {
		var i UploadRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.RowNumber,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadRowsByBatchAndValidation = `-- name: GetUploadRowsByBatchAndValidation :many
SELECT ur.id, ur.batch_id, ur.row_number, ur.data, ur.created_at FROM upload_rows ur
JOIN validation_results vr ON vr.row_id = ur.id
WHERE ur.batch_id = $1 AND vr.is_valid = $2 
ORDER BY ur.row_number
`

type GetUploadRowsByBatchAndValidationParams struct {
	BatchID uuid.UUID
	IsValid bool
}

func (q *Queries) GetUploadRowsByBatchAndValidation(ctx context.Context, arg GetUploadRowsByBatchAndValidationParams) ([]UploadRow, error) {
	rows, err := q.db.Query(ctx, getUploadRowsByBatchAndValidation, arg.BatchID, arg.IsValid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadRow
	for rows.Next() {
		var i UploadRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.RowNumber,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
