// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (org_id,email,name,role,password_hash)
VALUES($1,$2,$3,$4,$5)
RETURNING id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
`

type CreateUserParams struct {
	OrgID        uuid.UUID
	Email        string
	Name         string
	Role         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OrgID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}

const disableUserMFA = `-- name: DisableUserMFA :one
UPDATE users SET mfa_enabled = false, mfa_secret = NULL WHERE id = $1
RETURNING id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
`

func (q *Queries) DisableUserMFA(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, disableUserMFA, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}

const setUserMFA = `-- name: SetUserMFA :one
UPDATE users SET mfa_enabled = true, mfa_secret = $2 WHERE id = $1
RETURNING id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
`

type SetUserMFAParams struct {
	ID        uuid.UUID
	MfaSecret pgtype.Text
}

func (q *Queries) SetUserMFA(ctx context.Context, arg SetUserMFAParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserMFA, arg.ID, arg.MfaSecret)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}

const updateUserActive = `-- name: UpdateUserActive :one
UPDATE users SET active = $2 WHERE id = $1
RETURNING id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
`

type UpdateUserActiveParams struct {
	ID     uuid.UUID
	Active bool
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserActive, arg.ID, arg.Active)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $2 WHERE id = $1
RETURNING id, org_id, email, name, role, created_at, password_hash, failed_login_attempts, locked_until, mfa_enabled, mfa_secret, active
`

type UpdateUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.Active,
	)
	return i, err
}
